version: '3.7'
services:
  db:
    image: postgres:15
    container_name: file_processor_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-docker
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: file_processor_cache

  file_processor_drf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_processor_drf_app
    env_file:
      - .env-docker
    depends_on:
      db:
        condition: service_healthy
    command:
      - "docker/app.sh"
    ports:
      - "7777:8000"

  celery:
    build: .
    container_name: file_processor_celery
    env_file:
      - .env-docker
    command:
      - "docker/celery.sh"
    depends_on:
      - file_processor_drf
      - redis

volumes:
  postgresdata:
