# Generated by Django 5.0.2 on 2024-02-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="время обработки"
            ),
        ),
    ]
